-- ============================================================================
-- BANCO BANQUITO - CORE BANCARIO V2
-- Modelo fisico MySQL 8.0+ orientado a microservicios y DDD
-- Script: 01_core_customer_db.sql
-- Fecha: Mayo 2026
--
-- Principios aplicados:
-- - Database per Service: cada microservicio es propietario exclusivo de su BD.
-- - No existen FOREIGN KEY cruzadas entre bases de datos/microservicios.
-- - La trazabilidad entre servicios se mantiene con UUIDs, codigos funcionales,
--   referencias externas y UUID_CORRELACION.
-- - Enums implementados como VARCHAR + CHECK.
-- - InnoDB, utf8mb4, PK/FK/UK/CK nombradas explicitamente.
-- ============================================================================

CREATE DATABASE IF NOT EXISTS banquito_core_customer_db
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE banquito_core_customer_db;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS AUDITORIA_CUSTOMER_EVENTO;
DROP TABLE IF EXISTS CREDENCIAL_WEB;
DROP TABLE IF EXISTS CLIENTE_PERSONA_JURIDICA;
DROP TABLE IF EXISTS CLIENTE_PERSONA_NATURAL;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS SUBTIPO_CLIENTE;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE SUBTIPO_CLIENTE (
    ID INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador interno del subtipo de cliente',
    CODIGO VARCHAR(30) NOT NULL COMMENT 'Codigo funcional del segmento de cliente',
    TIPO_CLIENTE VARCHAR(15) NOT NULL COMMENT 'NATURAL o JURIDICO',
    NOMBRE VARCHAR(100) NOT NULL COMMENT 'Nombre comercial del subtipo',
    DESCRIPCION VARCHAR(300) NULL COMMENT 'Descripcion funcional del subtipo',
    ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO' COMMENT 'Estado del subtipo',
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion',
    FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Ultima actualizacion',
    VERSION INT NOT NULL DEFAULT 0 COMMENT 'Version para concurrencia optimista',
    CONSTRAINT PK_SUBTIPO_CLIENTE PRIMARY KEY (ID),
    CONSTRAINT UK_SUBTIPO_CLIENTE_CODIGO UNIQUE (CODIGO),
    CONSTRAINT CK_SUBTIPO_CLIENTE_TIPO CHECK (TIPO_CLIENTE IN ('NATURAL','JURIDICO')),
    CONSTRAINT CK_SUBTIPO_CLIENTE_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Catalogo de segmentos de clientes';

CREATE TABLE CLIENTE (
    ID INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador interno del cliente dentro del microservicio Customer',
    UUID_CLIENTE CHAR(36) NOT NULL COMMENT 'Identificador global del cliente para integracion entre microservicios',
    SUBTIPO_CLIENTE_ID INT NOT NULL COMMENT 'Subtipo de cliente',
    TIPO_CLIENTE VARCHAR(15) NOT NULL COMMENT 'NATURAL o JURIDICO',
    TIPO_IDENTIFICACION VARCHAR(15) NOT NULL COMMENT 'CEDULA, RUC o PASAPORTE',
    IDENTIFICACION VARCHAR(20) NOT NULL COMMENT 'Numero de identificacion oficial',
    EMAIL VARCHAR(120) NOT NULL COMMENT 'Correo electronico principal',
    TELEFONO_MOVIL VARCHAR(25) NOT NULL COMMENT 'Telefono movil principal',
    DIRECCION VARCHAR(300) NOT NULL COMMENT 'Direccion fisica principal',
    LATITUD DECIMAL(10,8) NULL COMMENT 'Latitud geografica opcional',
    LONGITUD DECIMAL(11,8) NULL COMMENT 'Longitud geografica opcional',
    ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO' COMMENT 'Estado del cliente',
    ACTIVO_PAGOS_MASIVOS TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Habilitacion de empresa para pagos masivos',
    FECHA_REGISTRO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de registro del cliente',
    FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Ultima actualizacion',
    VERSION INT NOT NULL DEFAULT 0 COMMENT 'Version para concurrencia optimista',
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID),
    CONSTRAINT UK_CLIENTE_UUID UNIQUE (UUID_CLIENTE),
    CONSTRAINT UK_CLIENTE_IDENTIFICACION UNIQUE (TIPO_IDENTIFICACION, IDENTIFICACION),
    CONSTRAINT FK_CLIENTE_SUBTIPO FOREIGN KEY (SUBTIPO_CLIENTE_ID) REFERENCES SUBTIPO_CLIENTE(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT CK_CLIENTE_TIPO CHECK (TIPO_CLIENTE IN ('NATURAL','JURIDICO')),
    CONSTRAINT CK_CLIENTE_TIPO_IDENTIFICACION CHECK (TIPO_IDENTIFICACION IN ('CEDULA','RUC','PASAPORTE')),
    CONSTRAINT CK_CLIENTE_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO','BLOQUEADO')),
    CONSTRAINT CK_CLIENTE_PAGOS_MASIVOS CHECK (ACTIVO_PAGOS_MASIVOS IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Cliente maestro del banco';

CREATE INDEX IX_CLIENTE_IDENTIFICACION ON CLIENTE (IDENTIFICACION);
CREATE INDEX IX_CLIENTE_TIPO_ESTADO ON CLIENTE (TIPO_CLIENTE, ESTADO);

CREATE TABLE CLIENTE_PERSONA_NATURAL (
    CLIENTE_ID INT NOT NULL COMMENT 'Cliente base asociado',
    NOMBRES VARCHAR(100) NOT NULL COMMENT 'Nombres de la persona natural',
    APELLIDOS VARCHAR(100) NOT NULL COMMENT 'Apellidos de la persona natural',
    FECHA_NACIMIENTO DATE NOT NULL COMMENT 'Fecha de nacimiento',
    CONSTRAINT PK_CLIENTE_PERSONA_NATURAL PRIMARY KEY (CLIENTE_ID),
    CONSTRAINT FK_CLIENTE_NATURAL_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Especializacion de cliente persona natural';

CREATE TABLE CLIENTE_PERSONA_JURIDICA (
    CLIENTE_ID INT NOT NULL COMMENT 'Cliente base asociado',
    RAZON_SOCIAL VARCHAR(180) NOT NULL COMMENT 'Razon social de la empresa',
    FECHA_CONSTITUCION DATE NOT NULL COMMENT 'Fecha de constitucion de la empresa',
    REPRESENTANTE_LEGAL_UUID CHAR(36) NOT NULL COMMENT 'UUID del cliente natural que representa legalmente a la empresa',
    REPRESENTANTE_LEGAL_IDENTIFICACION VARCHAR(20) NOT NULL COMMENT 'Identificacion denormalizada del representante para consulta rapida',
    CONSTRAINT PK_CLIENTE_PERSONA_JURIDICA PRIMARY KEY (CLIENTE_ID),
    CONSTRAINT FK_CLIENTE_JURIDICA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Especializacion de cliente persona juridica';

CREATE INDEX IX_CLIENTE_JURIDICA_REP_UUID ON CLIENTE_PERSONA_JURIDICA (REPRESENTANTE_LEGAL_UUID);

CREATE TABLE CREDENCIAL_WEB (
    ID INT AUTO_INCREMENT NOT NULL COMMENT 'Identificador interno de credencial',
    UUID_CREDENCIAL CHAR(36) NOT NULL COMMENT 'Identificador global de la credencial',
    CLIENTE_ID INT NOT NULL COMMENT 'Cliente propietario de la credencial',
    USUARIO VARCHAR(60) NOT NULL COMMENT 'Nombre de usuario para banca web',
    PASSWORD_HASH VARCHAR(255) NOT NULL COMMENT 'Hash de contrasena',
    ULTIMO_LOGIN DATETIME NULL COMMENT 'Ultimo inicio de sesion exitoso',
    INTENTOS_FALLIDOS INT NOT NULL DEFAULT 0 COMMENT 'Numero de intentos fallidos consecutivos',
    ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO' COMMENT 'Estado de la credencial',
    FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha de creacion',
    FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Ultima actualizacion',
    VERSION INT NOT NULL DEFAULT 0 COMMENT 'Version para concurrencia optimista',
    CONSTRAINT PK_CREDENCIAL_WEB PRIMARY KEY (ID),
    CONSTRAINT UK_CREDENCIAL_WEB_UUID UNIQUE (UUID_CREDENCIAL),
    CONSTRAINT UK_CREDENCIAL_WEB_USUARIO UNIQUE (USUARIO),
    CONSTRAINT FK_CREDENCIAL_WEB_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT CK_CREDENCIAL_WEB_ESTADO CHECK (ESTADO IN ('ACTIVO','BLOQUEADO','INACTIVO')),
    CONSTRAINT CK_CREDENCIAL_WEB_INTENTOS CHECK (INTENTOS_FALLIDOS >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Credenciales web asociadas a clientes';

CREATE TABLE AUDITORIA_CUSTOMER_EVENTO (
    ID BIGINT AUTO_INCREMENT NOT NULL COMMENT 'Identificador del evento auditado',
    UUID_CORRELACION CHAR(36) NULL COMMENT 'Correlation ID para trazabilidad distribuida',
    MODULO VARCHAR(60) NOT NULL COMMENT 'Modulo de customer-service',
    ACCION VARCHAR(100) NOT NULL COMMENT 'Accion ejecutada',
    ENTIDAD VARCHAR(80) NOT NULL COMMENT 'Entidad afectada',
    ENTIDAD_ID VARCHAR(100) NULL COMMENT 'Identificador de entidad afectada',
    RESULTADO VARCHAR(20) NOT NULL DEFAULT 'EXITOSO' COMMENT 'Resultado del evento',
    CANAL_ORIGEN VARCHAR(25) NOT NULL DEFAULT 'CUSTOMER_SERVICE' COMMENT 'Canal o sistema origen',
    IP_ORIGEN VARCHAR(45) NULL COMMENT 'Direccion IP origen',
    DETALLE_JSON JSON NULL COMMENT 'Detalle flexible del evento',
    FECHA_EVENTO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha y hora del evento',
    CONSTRAINT PK_AUDITORIA_CUSTOMER_EVENTO PRIMARY KEY (ID),
    CONSTRAINT CK_AUDITORIA_CUSTOMER_RESULTADO CHECK (RESULTADO IN ('EXITOSO','FALLIDO','RECHAZADO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Auditoria local del microservicio de clientes';

CREATE INDEX IX_AUDITORIA_CUSTOMER_FECHA ON AUDITORIA_CUSTOMER_EVENTO (FECHA_EVENTO);
CREATE INDEX IX_AUDITORIA_CUSTOMER_CORR ON AUDITORIA_CUSTOMER_EVENTO (UUID_CORRELACION);

INSERT INTO SUBTIPO_CLIENTE (ID, CODIGO, TIPO_CLIENTE, NOMBRE, DESCRIPCION) VALUES
(1, 'NAT_ESTANDAR', 'NATURAL', 'Natural Estandar', 'Persona natural estandar'),
(2, 'JUR_EMPRESA', 'JURIDICO', 'Empresa', 'Persona juridica corporativa');
