-- ============================================================================
-- BANCO BANQUITO V2 - CORE CUSTOMER SERVICE
-- Modelo fisico MySQL 8.4 LTS
-- Base: banquito_core_customer_db
-- Proposito: clientes naturales/juridicos, relaciones de titularidad y auditoria.
-- ============================================================================
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS SUBTIPO_CLIENTE (
  ID INT AUTO_INCREMENT NOT NULL,
  CODIGO VARCHAR(30) NOT NULL,
  TIPO_CLIENTE VARCHAR(15) NOT NULL,
  NOMBRE VARCHAR(100) NOT NULL,
  DESCRIPCION VARCHAR(300) NULL,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVO',
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_SUBTIPO_CLIENTE PRIMARY KEY (ID),
  CONSTRAINT UK_SUBTIPO_CLIENTE_CODIGO UNIQUE (CODIGO),
  CONSTRAINT CK_SUBTIPO_CLIENTE_TIPO CHECK (TIPO_CLIENTE IN ('NATURAL','JURIDICO')),
  CONSTRAINT CK_SUBTIPO_CLIENTE_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Segmentos comerciales de clientes';

CREATE TABLE IF NOT EXISTS CLIENTE (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_CLIENTE CHAR(36) NOT NULL,
  UUID_IDENTIDAD_PRINCIPAL CHAR(36) NULL COMMENT 'Referencia a identity-access-service; sin FK cruzada',
  SUBTIPO_CLIENTE_ID INT NOT NULL,
  TIPO_CLIENTE VARCHAR(15) NOT NULL,
  TIPO_IDENTIFICACION VARCHAR(15) NOT NULL,
  IDENTIFICACION VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(160) NOT NULL,
  TELEFONO_MOVIL VARCHAR(25) NOT NULL,
  DIRECCION VARCHAR(300) NOT NULL,
  ESTADO VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
  ACTIVO_PAGOS_MASIVOS TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Empresa habilitada para pagos masivos',
  FECHA_ALTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_CLIENTE PRIMARY KEY (ID),
  CONSTRAINT UK_CLIENTE_UUID UNIQUE (UUID_CLIENTE),
  CONSTRAINT UK_CLIENTE_IDENT UNIQUE (TIPO_IDENTIFICACION, IDENTIFICACION),
  CONSTRAINT FK_CLIENTE_SUBTIPO FOREIGN KEY (SUBTIPO_CLIENTE_ID) REFERENCES SUBTIPO_CLIENTE(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT CK_CLIENTE_TIPO CHECK (TIPO_CLIENTE IN ('NATURAL','JURIDICO')),
  CONSTRAINT CK_CLIENTE_IDENT CHECK (TIPO_IDENTIFICACION IN ('CEDULA','RUC','PASAPORTE')),
  CONSTRAINT CK_CLIENTE_ESTADO CHECK (ESTADO IN ('ACTIVO','INACTIVO','BLOQUEADO','SUSPENDIDO')),
  CONSTRAINT CK_CLIENTE_PAGOS_MASIVOS CHECK ((TIPO_CLIENTE='JURIDICO') OR (ACTIVO_PAGOS_MASIVOS=0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Entidad maestra de cliente';

CREATE TABLE IF NOT EXISTS CLIENTE_PERSONA_NATURAL (
  CLIENTE_ID BIGINT NOT NULL,
  NOMBRES VARCHAR(120) NOT NULL,
  APELLIDOS VARCHAR(120) NOT NULL,
  FECHA_NACIMIENTO DATE NOT NULL,
  GENERO VARCHAR(20) NULL,
  NACIONALIDAD VARCHAR(80) NULL,
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_CLIENTE_PERSONA_NATURAL PRIMARY KEY (CLIENTE_ID),
  CONSTRAINT FK_CPN_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT CK_CPN_GENERO CHECK (GENERO IS NULL OR GENERO IN ('MASCULINO','FEMENINO','OTRO','NO_DECLARA'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Datos especificos de persona natural';

CREATE TABLE IF NOT EXISTS CLIENTE_PERSONA_JURIDICA (
  CLIENTE_ID BIGINT NOT NULL,
  RAZON_SOCIAL VARCHAR(180) NOT NULL,
  NOMBRE_COMERCIAL VARCHAR(180) NULL,
  FECHA_CONSTITUCION DATE NOT NULL,
  ACTIVIDAD_ECONOMICA VARCHAR(200) NULL,
  REPRESENTANTE_LEGAL_UUID CHAR(36) NULL COMMENT 'Referencia al UUID_CLIENTE de persona natural representante; sin FK para flexibilidad',
  REPRESENTANTE_LEGAL_IDENTIFICACION VARCHAR(20) NULL,
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT PK_CLIENTE_PERSONA_JURIDICA PRIMARY KEY (CLIENTE_ID),
  CONSTRAINT FK_CPJ_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Datos especificos de persona juridica';

CREATE TABLE IF NOT EXISTS CLIENTE_RELACION (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_RELACION CHAR(36) NOT NULL,
  UUID_CLIENTE_ORIGEN CHAR(36) NOT NULL COMMENT 'Cliente juridico o entidad principal',
  UUID_CLIENTE_RELACIONADO CHAR(36) NOT NULL COMMENT 'Cliente/persona relacionada',
  TIPO_RELACION VARCHAR(40) NOT NULL COMMENT 'REPRESENTANTE_LEGAL, APODERADO, CONTACTO_AUTORIZADO, BENEFICIARIO_FINAL, ACCIONISTA',
  IDENTIFICACION_RELACIONADA VARCHAR(20) NULL,
  NOMBRE_RELACIONADO VARCHAR(180) NULL,
  FECHA_INICIO DATE NOT NULL,
  FECHA_FIN DATE NULL,
  ESTADO VARCHAR(15) NOT NULL DEFAULT 'ACTIVA',
  OBSERVACION VARCHAR(500) NULL,
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_CLIENTE_RELACION PRIMARY KEY (ID),
  CONSTRAINT UK_CLIENTE_RELACION_UUID UNIQUE (UUID_RELACION),
  CONSTRAINT UK_CLIENTE_RELACION_ACTIVA UNIQUE (UUID_CLIENTE_ORIGEN, UUID_CLIENTE_RELACIONADO, TIPO_RELACION, FECHA_INICIO),
  CONSTRAINT CK_CLIENTE_RELACION_TIPO CHECK (TIPO_RELACION IN ('REPRESENTANTE_LEGAL','APODERADO','CONTACTO_AUTORIZADO','BENEFICIARIO_FINAL','ACCIONISTA')),
  CONSTRAINT CK_CLIENTE_RELACION_ESTADO CHECK (ESTADO IN ('ACTIVA','INACTIVA','REVOCADA','VENCIDA')),
  CONSTRAINT CK_CLIENTE_RELACION_FECHAS CHECK (FECHA_FIN IS NULL OR FECHA_FIN >= FECHA_INICIO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Relaciones entre clientes; representante legal y otros roles';

CREATE TABLE IF NOT EXISTS AUDITORIA_CUSTOMER_EVENTO (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_CORRELACION CHAR(36) NULL,
  UUID_USUARIO CHAR(36) NULL,
  MODULO VARCHAR(60) NOT NULL,
  ACCION VARCHAR(80) NOT NULL,
  ENTIDAD VARCHAR(80) NOT NULL,
  ENTIDAD_ID VARCHAR(80) NULL,
  RESULTADO VARCHAR(15) NOT NULL,
  CANAL_ORIGEN VARCHAR(30) NULL,
  IP_ORIGEN VARCHAR(45) NULL,
  DETALLE_JSON JSON NULL,
  FECHA_EVENTO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_AUDITORIA_CUSTOMER PRIMARY KEY (ID),
  CONSTRAINT CK_AUDITORIA_CUSTOMER_RESULTADO CHECK (RESULTADO IN ('OK','ERROR','DENEGADO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Auditoria local de customer-service';

CREATE TABLE IF NOT EXISTS OUTBOX_EVENT (
  ID BIGINT AUTO_INCREMENT NOT NULL,
  UUID_EVENTO CHAR(36) NOT NULL,
  UUID_CORRELACION CHAR(36) NULL,
  TIPO_EVENTO VARCHAR(80) NOT NULL,
  AGREGADO_TIPO VARCHAR(80) NOT NULL,
  AGREGADO_ID VARCHAR(80) NOT NULL,
  PAYLOAD_JSON JSON NOT NULL,
  ESTADO VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
  INTENTOS INT NOT NULL DEFAULT 0,
  FECHA_CREACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_PUBLICACION DATETIME NULL,
  ERROR_ULTIMO VARCHAR(1000) NULL,
  CONSTRAINT PK_OUTBOX_CUSTOMER PRIMARY KEY (ID),
  CONSTRAINT UK_OUTBOX_CUSTOMER_UUID UNIQUE (UUID_EVENTO),
  CONSTRAINT CK_OUTBOX_CUSTOMER_ESTADO CHECK (ESTADO IN ('PENDIENTE','PUBLICADO','ERROR','DESCARTADO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Eventos confiables del customer-service';

CREATE INDEX IDX_CLIENTE_IDENTIFICACION ON CLIENTE(IDENTIFICACION);
CREATE INDEX IDX_CLIENTE_UUID_IDENTIDAD ON CLIENTE(UUID_IDENTIDAD_PRINCIPAL);
CREATE INDEX IDX_RELACION_ORIGEN ON CLIENTE_RELACION(UUID_CLIENTE_ORIGEN, TIPO_RELACION, ESTADO);
CREATE INDEX IDX_OUTBOX_CUSTOMER_ESTADO ON OUTBOX_EVENT(ESTADO, FECHA_CREACION);
